name: PR Test CI


on:
  pull_request_target:
    branches: [ main ]

# Ensures that only one deploy task per branch/environment will run at a time. 
concurrency:
  group: functional-environment
  cancel-in-progress: false
  
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Test Step
        run: |
          echo 'Test Step: The label is present once1'
          sleep 300
