name: PR Test CI


on:
  pull_request_target:
    branches: [ main ]
  workflow_dispatch:

# Ensures that only one deploy task per branch/environment will run at a time. 
concurrency:
  group: functional-environment
  cancel-in-progress: false
  
jobs:
  approve: # First step
    runs-on: ubuntu-latest
    steps:
      - name: Approve
        run: echo For security reasons, all pull requests need to be approved first before running any automated CI.

  unittest:
    # run all python versions, in other jobs run the latest python
    name: unittest
    needs: [ approve ] # Require the first step to finish
    environment:
      name: Integrate Pull Request # Our protected environment variable
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: 
           - '3.7'
           - '3.8'
           - '3.9'
           - '3.10'
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ok-to-test') }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest pytest-cov
      - name: run echo
        run: |
            echo 'Test1'

  integration_test:
    needs: [approve, unittest]
    runs-on: ubuntu-latest
    steps:
      - name: Test Step
        run: |
          echo 'Test Step: integration_test'

  e2e:
    needs: [approve, unittest, integration_test]
    runs-on: ubuntu-latest
    steps:
      - name: Test Step
        run: |
          echo 'Test Step: The label is present once1
